version: "3.9"

services:
  database:
    env_file: ".env.local"
    image: postgres:12-alpine
    restart: always
    container_name: database
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432

  keycloak:
    env_file: ".env.local"
    image: quay.io/keycloak/keycloak:25.0
    restart: always
    container_name: keycloak
    command: ["start-dev"]
    volumes:
      - ./certs:/etc/certs
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DATABASE_NAME: keycloak

      KC_HOSTNAME: localhost
      # KC_HTTPS_PORT: 443
      KC_PROXY_HEADERS: xforwarded
      KC_HTTPS_CERTIFICATE_FILE: /etc/certs/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/certs/tls.key
      KC_HTTP_ENABLED: true

    ports:
      - 8443:8443
      - 8080:8080
    depends_on:
      - database

  # web:
  #   image: nginx
  #   container_name: nginx-web-app
  #   ports:
  #     - 3000:80
  #   environment:
  #     - NGINX_HOST=localhost.co
  #     - NGINX_PORT=80
